
package dk.ihedge.finance.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Wed May 29 21:33:21 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "confirmSecuritiesResponse", namespace = "http://finance.ihedge.dk/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confirmSecuritiesResponse", namespace = "http://finance.ihedge.dk/")

public class ConfirmSecuritiesResponse {

    @XmlElement(name = "return")
    private dk.ihedge.finance.dtl.TransactionReport _return;

    public dk.ihedge.finance.dtl.TransactionReport getReturn() {
        return this._return;
    }

    public void setReturn(dk.ihedge.finance.dtl.TransactionReport new_return)  {
        this._return = new_return;
    }

}

