
package dk.ihedge.finance.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Wed May 29 21:33:20 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "createPortfolio", namespace = "http://finance.ihedge.dk/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createPortfolio", namespace = "http://finance.ihedge.dk/", propOrder = {"login", "portfolioTitle", "startCash"})

public class CreatePortfolio {

    @XmlElement(name = "login")
    private java.lang.String login;
    @XmlElement(name = "portfolioTitle")
    private java.lang.String portfolioTitle;
    @XmlElement(name = "startCash")
    private double startCash;

    public java.lang.String getLogin() {
        return this.login;
    }

    public void setLogin(java.lang.String newLogin)  {
        this.login = newLogin;
    }

    public java.lang.String getPortfolioTitle() {
        return this.portfolioTitle;
    }

    public void setPortfolioTitle(java.lang.String newPortfolioTitle)  {
        this.portfolioTitle = newPortfolioTitle;
    }

    public double getStartCash() {
        return this.startCash;
    }

    public void setStartCash(double newStartCash)  {
        this.startCash = newStartCash;
    }

}

