
package dk.ihedge.finance.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Wed May 29 21:33:21 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "createTournament", namespace = "http://finance.ihedge.dk/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createTournament", namespace = "http://finance.ihedge.dk/", propOrder = {"login", "tournament"})

public class CreateTournament {

    @XmlElement(name = "login")
    private java.lang.String login;
    @XmlElement(name = "tournament")
    private dk.ihedge.finance.dtl.Tournament tournament;

    public java.lang.String getLogin() {
        return this.login;
    }

    public void setLogin(java.lang.String newLogin)  {
        this.login = newLogin;
    }

    public dk.ihedge.finance.dtl.Tournament getTournament() {
        return this.tournament;
    }

    public void setTournament(dk.ihedge.finance.dtl.Tournament newTournament)  {
        this.tournament = newTournament;
    }

}

