
package dk.ihedge.finance.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Wed May 29 21:33:21 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "getUnconfirmedSecuritiesResponse", namespace = "http://finance.ihedge.dk/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUnconfirmedSecuritiesResponse", namespace = "http://finance.ihedge.dk/")

public class GetUnconfirmedSecuritiesResponse {

    @XmlElement(name = "return")
    private java.util.List<dk.ihedge.finance.dtl.Security> _return;

    public java.util.List<dk.ihedge.finance.dtl.Security> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<dk.ihedge.finance.dtl.Security> new_return)  {
        this._return = new_return;
    }

}

