
package dk.ihedge.finance.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Wed May 29 21:33:21 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "leaveTournament", namespace = "http://finance.ihedge.dk/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaveTournament", namespace = "http://finance.ihedge.dk/", propOrder = {"login", "tournamentID"})

public class LeaveTournament {

    @XmlElement(name = "login")
    private java.lang.String login;
    @XmlElement(name = "tournamentID")
    private int tournamentID;

    public java.lang.String getLogin() {
        return this.login;
    }

    public void setLogin(java.lang.String newLogin)  {
        this.login = newLogin;
    }

    public int getTournamentID() {
        return this.tournamentID;
    }

    public void setTournamentID(int newTournamentID)  {
        this.tournamentID = newTournamentID;
    }

}

