//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagerWSClient.InvestmentManagerWSStub {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://finance.ihedge.dk/", ConfigurationName="InvestmentManagerWSStub.InvestmentManagerInterface")]
    public interface InvestmentManagerInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void helloWorld();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getCategoriesResponse getCategories(InvestmentManagerWSClient.InvestmentManagerWSStub.getCategories request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetPortfolio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolioResponse getPortfolio(InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolio request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetAssets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getAssetsResponse getAssets(InvestmentManagerWSClient.InvestmentManagerWSStub.getAssets request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetPortfolios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfoliosResponse getPortfolios(InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolios request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://finance.ihedge.dk/")]
    public partial class category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://finance.ihedge.dk/")]
    public partial class asset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private double quoteField;
        
        private string symbolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double quote {
            get {
                return this.quoteField;
            }
            set {
                this.quoteField = value;
                this.RaisePropertyChanged("quote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("symbol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://finance.ihedge.dk/")]
    public partial class security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double anualVolatilityField;
        
        private double avgVoltatilityField;
        
        private double dailyVolatilityField;
        
        private double marketValueField;
        
        private int positionField;
        
        private double purchaceQuoteField;
        
        private double purchaseAmountField;
        
        private double quoteField;
        
        private string symbolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double anualVolatility {
            get {
                return this.anualVolatilityField;
            }
            set {
                this.anualVolatilityField = value;
                this.RaisePropertyChanged("anualVolatility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double avgVoltatility {
            get {
                return this.avgVoltatilityField;
            }
            set {
                this.avgVoltatilityField = value;
                this.RaisePropertyChanged("avgVoltatility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double dailyVolatility {
            get {
                return this.dailyVolatilityField;
            }
            set {
                this.dailyVolatilityField = value;
                this.RaisePropertyChanged("dailyVolatility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double marketValue {
            get {
                return this.marketValueField;
            }
            set {
                this.marketValueField = value;
                this.RaisePropertyChanged("marketValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double purchaceQuote {
            get {
                return this.purchaceQuoteField;
            }
            set {
                this.purchaceQuoteField = value;
                this.RaisePropertyChanged("purchaceQuote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double purchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("purchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double quote {
            get {
                return this.quoteField;
            }
            set {
                this.quoteField = value;
                this.RaisePropertyChanged("quote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("symbol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://finance.ihedge.dk/")]
    public partial class portfolio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private security[] securitiesField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("securities", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public security[] securities {
            get {
                return this.securitiesField;
            }
            set {
                this.securitiesField = value;
                this.RaisePropertyChanged("securities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategories", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getCategories {
        
        public getCategories() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategoriesResponse", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public category[] @return;
        
        public getCategoriesResponse() {
        }
        
        public getCategoriesResponse(category[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPortfolio", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getPortfolio {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getPortfolio() {
        }
        
        public getPortfolio(string arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPortfolioResponse", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getPortfolioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvestmentManagerWSClient.InvestmentManagerWSStub.portfolio @return;
        
        public getPortfolioResponse() {
        }
        
        public getPortfolioResponse(InvestmentManagerWSClient.InvestmentManagerWSStub.portfolio @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAssets", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getAssets {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getAssets() {
        }
        
        public getAssets(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAssetsResponse", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getAssetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public asset[] @return;
        
        public getAssetsResponse() {
        }
        
        public getAssetsResponse(asset[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPortfolios", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getPortfolios {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPortfolios() {
        }
        
        public getPortfolios(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPortfoliosResponse", WrapperNamespace="http://finance.ihedge.dk/", IsWrapped=true)]
    public partial class getPortfoliosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://finance.ihedge.dk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolio[] @return;
        
        public getPortfoliosResponse() {
        }
        
        public getPortfoliosResponse(portfolio[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvestmentManagerInterfaceChannel : InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvestmentManagerInterfaceClient : System.ServiceModel.ClientBase<InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface>, InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface {
        
        public InvestmentManagerInterfaceClient() {
        }
        
        public InvestmentManagerInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvestmentManagerInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvestmentManagerInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvestmentManagerInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void helloWorld() {
            base.Channel.helloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getCategoriesResponse InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface.getCategories(InvestmentManagerWSClient.InvestmentManagerWSStub.getCategories request) {
            return base.Channel.getCategories(request);
        }
        
        public category[] getCategories() {
            InvestmentManagerWSClient.InvestmentManagerWSStub.getCategories inValue = new InvestmentManagerWSClient.InvestmentManagerWSStub.getCategories();
            InvestmentManagerWSClient.InvestmentManagerWSStub.getCategoriesResponse retVal = ((InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface)(this)).getCategories(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolioResponse InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface.getPortfolio(InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolio request) {
            return base.Channel.getPortfolio(request);
        }
        
        public InvestmentManagerWSClient.InvestmentManagerWSStub.portfolio getPortfolio(string arg0, int arg1) {
            InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolio inValue = new InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolio();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolioResponse retVal = ((InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface)(this)).getPortfolio(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getAssetsResponse InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface.getAssets(InvestmentManagerWSClient.InvestmentManagerWSStub.getAssets request) {
            return base.Channel.getAssets(request);
        }
        
        public asset[] getAssets(int arg0) {
            InvestmentManagerWSClient.InvestmentManagerWSStub.getAssets inValue = new InvestmentManagerWSClient.InvestmentManagerWSStub.getAssets();
            inValue.arg0 = arg0;
            InvestmentManagerWSClient.InvestmentManagerWSStub.getAssetsResponse retVal = ((InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface)(this)).getAssets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfoliosResponse InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface.getPortfolios(InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolios request) {
            return base.Channel.getPortfolios(request);
        }
        
        public portfolio[] getPortfolios(string arg0) {
            InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolios inValue = new InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfolios();
            inValue.arg0 = arg0;
            InvestmentManagerWSClient.InvestmentManagerWSStub.getPortfoliosResponse retVal = ((InvestmentManagerWSClient.InvestmentManagerWSStub.InvestmentManagerInterface)(this)).getPortfolios(inValue);
            return retVal.@return;
        }
    }
}
